//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Securypt.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_link {
            get {
                return ResourceManager.GetString("About_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the download page, you can view, edit, and manage your files..
        /// </summary>
        public static string About_p1 {
            get {
                return ResourceManager.GetString("About_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently, all your uploaded files are private, meaning only you can view them. If you wish to change this select the &quot;Edit&quot; button and uncheck the private box..
        /// </summary>
        public static string About_p2 {
            get {
                return ResourceManager.GetString("About_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string BrowseFiles {
            get {
                return ResourceManager.GetString("BrowseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact the administrator for any questions or concerns..
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact_link {
            get {
                return ResourceManager.GetString("Contact_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An authorized party, however, is able to decode the ciphertext using a decryption algorithm, that usually requires a secret decryption key, that adversaries do not have access to. For technical reasons, an encryption scheme usually needs a key-generation algorithm, to randomly produce keys..
        /// </summary>
        public static string Decrypt_desc {
            get {
                return ResourceManager.GetString("Decrypt_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        public static string DecryptH2 {
            get {
                return ResourceManager.GetString("DecryptH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Decrypting!.
        /// </summary>
        public static string DecryptHome_btn {
            get {
                return ResourceManager.GetString("DecryptHome_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download_link {
            get {
                return ResourceManager.GetString("Download_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop your files here.
        /// </summary>
        public static string DragArea {
            get {
                return ResourceManager.GetString("DragArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag &amp; Drop file upload.
        /// </summary>
        public static string DragDropH2 {
            get {
                return ResourceManager.GetString("DragDropH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In cryptography, encryption is the process of encoding a message or information in such a way that only authorized parties can access it. Encryption does not itself prevent interference, but denies the intelligible content to a would-be interceptor. In an encryption scheme, the intended information or message, referred to as plaintext, is encrypted using an encryption algorithm – a cipher – generating ciphertext that can only be read if decrypted..
        /// </summary>
        public static string Encrypt_desc {
            get {
                return ResourceManager.GetString("Encrypt_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        public static string EncryptH2 {
            get {
                return ResourceManager.GetString("EncryptH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Encrypting!.
        /// </summary>
        public static string EncryptHome_btn {
            get {
                return ResourceManager.GetString("EncryptHome_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        public static string EncryptUpload_btn {
            get {
                return ResourceManager.GetString("EncryptUpload_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ForgotViewModel_displayEmail {
            get {
                return ResourceManager.GetString("ForgotViewModel_displayEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_link {
            get {
                return ResourceManager.GetString("Home_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to start.
        /// </summary>
        public static string HowStartH2 {
            get {
                return ResourceManager.GetString("HowStartH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Items_create {
            get {
                return ResourceManager.GetString("Items_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Items_delete {
            get {
                return ResourceManager.GetString("Items_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Items_details {
            get {
                return ResourceManager.GetString("Items_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Items_edit {
            get {
                return ResourceManager.GetString("Items_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Items_name {
            get {
                return ResourceManager.GetString("Items_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key.
        /// </summary>
        public static string Items_publicKey {
            get {
                return ResourceManager.GetString("Items_publicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Location.
        /// </summary>
        public static string Items_storageLoc {
            get {
                return ResourceManager.GetString("Items_storageLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string Jumbo_btn {
            get {
                return ResourceManager.GetString("Jumbo_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Securypt allows you to encrypt and decrypt your files. Files may be saved locally or stored on a server. Create an account for a public key.
        /// </summary>
        public static string Jumbotron {
            get {
                return ResourceManager.GetString("Jumbotron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string Manage_changePassActLink {
            get {
                return ResourceManager.GetString("Manage_changePassActLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Manage_createActLink {
            get {
                return ResourceManager.GetString("Manage_createActLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage_manageActLink {
            get {
                return ResourceManager.GetString("Manage_manageActLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key.
        /// </summary>
        public static string Manage_publicKey {
            get {
                return ResourceManager.GetString("Manage_publicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string ManageH4 {
            get {
                return ResourceManager.GetString("ManageH4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Shared_greeting {
            get {
                return ResourceManager.GetString("Shared_greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get started, register for an account and begin uploading and downloading files. Search friends or colleagues by email to share your files with them..
        /// </summary>
        public static string Tutorial_pt1 {
            get {
                return ResourceManager.GetString("Tutorial_pt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the &apos;Upload&apos; tab to start. Drag and drop or upload files from your computer onto the upload area. Once all your files have been selected, click &quot;Encrypt&quot; to encrypt your files. After, your encrypted files will be stored locally on your computer or you can choose to store them on a server..
        /// </summary>
        public static string Tutorial_pt2 {
            get {
                return ResourceManager.GetString("Tutorial_pt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our encryption server will decrypt your files and serve them to you over the widespread HTTPS protocol, keeping your data secure..
        /// </summary>
        public static string Tutorial_pt3 {
            get {
                return ResourceManager.GetString("Tutorial_pt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To permit other users to use your file go to the Download page and next to the file you wish to allow other users access to click &quot;Edit&quot;. Uncheck the &quot;Private&quot; box and save. Back on the Upload page click &quot;Details&quot; and then click &quot;Permitted Users&quot;. Click &quot;Add Permission&quot; and then enter the email address of the person you wish to share your file with..
        /// </summary>
        public static string Tutorial_pt4 {
            get {
                return ResourceManager.GetString("Tutorial_pt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or upload your files here.
        /// </summary>
        public static string Upload_alt {
            get {
                return ResourceManager.GetString("Upload_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload_link {
            get {
                return ResourceManager.GetString("Upload_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file(s) uploaded successfully.
        /// </summary>
        public static string Upload_success {
            get {
                return ResourceManager.GetString("Upload_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded Files.
        /// </summary>
        public static string UploadedFilesH2 {
            get {
                return ResourceManager.GetString("UploadedFilesH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Wikipedia, the free encyclopedia.
        /// </summary>
        public static string Wikipedia {
            get {
                return ResourceManager.GetString("Wikipedia", resourceCulture);
            }
        }
    }
}
