using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SecuryptMVC.Models
{
    public class EncryptedItem
    {
		/// <summary>
		/// Unique ID auto-generated by Entity Framework
		/// </summary>
        public int		ID				{ get; set; }

		/// <summary>
		/// Whether or not EncryptedItem is private to user
		/// </summary>
        public bool		IsPrivate		{ get; set; }

		/// <summary>
		/// Filename available for searching
		/// </summary>
        public string	Name			{ get; set; }

		/// <summary>
		/// User's public key. Linked to EncryptedItem in UploadController Upload Action
		/// </summary>
        public string	PublicKey		{ get; set; }

		/// <summary>
		/// File 
		/// </summary>
        public string	StorageLocation { get; set; }
    }
}