//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Securypt.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyStrings_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecuryptMVC.Views.Shared.MyStrings-de", typeof(MyStrings_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateien.
        /// </summary>
        internal static string BrowseFiles {
            get {
                return ResourceManager.GetString("BrowseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine autorisierte Partei ist jedoch in der Lage, den Chiffretext unter Verwendung eines Entschlüsselungsalgorithmus zu decodieren, der normalerweise einen geheimen Entschlüsselungsschlüssel erfordert.
        ///             auf die Gegner keinen Zugriff haben. Aus technischen Gründen benötigt ein Verschlüsselungsschema normalerweise einen Schlüsselerzeugungsalgorithmus, um Schlüssel zufällig zu erzeugen..
        /// </summary>
        internal static string Decrypt_desc {
            get {
                return ResourceManager.GetString("Decrypt_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entschlüsseln.
        /// </summary>
        internal static string DecryptH2 {
            get {
                return ResourceManager.GetString("DecryptH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entschlüsselung starten.
        /// </summary>
        internal static string DecryptHome_btn {
            get {
                return ResourceManager.GetString("DecryptHome_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziehe deine Dateien per Drag &amp; Drop hier.
        /// </summary>
        internal static string DragArea {
            get {
                return ResourceManager.GetString("DragArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag &amp; Drop Datei-Upload.
        /// </summary>
        internal static string DragDropH2 {
            get {
                return ResourceManager.GetString("DragDropH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschlüsselung ist in der Kryptographie der Prozess der Verschlüsselung einer Nachricht oder Information so, dass nur autorisierte
        ///            Parteien können darauf zugreifen. Die Verschlüsselung verhindert selbst keine Interferenz, verweigert jedoch den verständlichen Inhalt einem möglichen Abfangjäger.
        ///            In einem Verschlüsselungsschema wird die beabsichtigte Information oder Nachricht, die als Klartext bezeichnet wird, unter Verwendung einer Verschlüsselung verschlüsselt.
        ///            Algori [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Encrypt_desc {
            get {
                return ResourceManager.GetString("Encrypt_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschlüsseln.
        /// </summary>
        internal static string EncryptH2 {
            get {
                return ResourceManager.GetString("EncryptH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschlüsseln starten.
        /// </summary>
        internal static string EncryptHome_btn {
            get {
                return ResourceManager.GetString("EncryptHome_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschlüsseln.
        /// </summary>
        internal static string EncryptUpload_btn {
            get {
                return ResourceManager.GetString("EncryptUpload_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie man anfängt.
        /// </summary>
        internal static string HowStartH2 {
            get {
                return ResourceManager.GetString("HowStartH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loslegen.
        /// </summary>
        internal static string Jumbo_btn {
            get {
                return ResourceManager.GetString("Jumbo_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit Securypt können Sie Ihre Dateien verschlüsseln und entschlüsseln. Dateien können lokal gespeichert oder auf einem Server gespeichert werden. Erstellen Sie ein Konto für einen öffentlichen Schlüssel.
        /// </summary>
        internal static string Jumbotron {
            get {
                return ResourceManager.GetString("Jumbotron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren Sie sich zunächst für ein Konto, um Ihren öffentlichen Schlüssel zu generieren. Bewahren Sie dieses irgendwo auf, wo Sie es nicht verlieren werden..
        /// </summary>
        internal static string Tutorial_pt1 {
            get {
                return ResourceManager.GetString("Tutorial_pt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Sie zum Starten auf die Registerkarte &quot;Hochladen&quot;. Ziehen Sie Dateien von Ihrem Computer in den Upload-Bereich und legen Sie sie dort ab. Sobald alle Ihre Dateien
        ///             Klicken Sie auf &quot;Verschlüsseln&quot;, um Ihre Dateien zu verschlüsseln. Danach werden Ihre verschlüsselten Dateien lokal gespeichert
        ///             auf Ihrem Computer oder Sie können wählen, sie auf einem Server zu speichern..
        /// </summary>
        internal static string Tutorial_pt2 {
            get {
                return ResourceManager.GetString("Tutorial_pt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Entschlüsselung Ihrer Dateien ist genauso einfach. Ziehen Sie Ihre verschlüsselten Dateien per Drag &amp; Drop oder laden Sie sie hoch, um sie zu entschlüsseln..
        /// </summary>
        internal static string Tutorial_pt3 {
            get {
                return ResourceManager.GetString("Tutorial_pt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oder laden Sie Ihre Dateien hier hoch.
        /// </summary>
        internal static string Upload_alt {
            get {
                return ResourceManager.GetString("Upload_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochgeladene Dateien.
        /// </summary>
        internal static string UploadedFilesH2 {
            get {
                return ResourceManager.GetString("UploadedFilesH2", resourceCulture);
            }
        }
    }
}
